package main

const tmpl = `
// Code generated by gogetter. DO NOT EDIT.
// Source: {{.Source}}

// Package {{.Package}} is generated by gogetter.
package {{.Package}}

import (
	{{range .Imports}}{{.Name}} {{.Path}}
	{{end}}
)

{{range .Structs}}
{{$type := .Name}}
// Getter for {{.Name}}
{{range .Fields}}
func (x *{{$type}}) Get{{.Name}}() {{.Type}} {
	if x != nil {
		return x.{{.Name}}
	}

	return {{.ZeroValue}}
}
{{end}}

{{end}}
`
